
// // utils/invoiceEmailService.js
// // Email service with PDF fallback for Windows stability

// let nodemailer;
// try {
//   nodemailer = require('nodemailer');
//   console.log('✓ Nodemailer loaded successfully');
// } catch (err) {
//   console.error('✗ Failed to load nodemailer:', err.message);
//   console.error('  Run: npm install nodemailer');
// }

// const logger = require('./logger');
// const { generateInvoicePDF } = require('./pdfGenerator');
// /**
//  * Parse CC emails from ENV
//  */
// const getInvoiceCCEmails = () => {
//   const cc = process.env.ADMIN_CC_EMAIL;
//   if (!cc) return undefined;

//   return cc
//     .split(',')
//     .map(e => e.trim())
//     .filter(Boolean);
// };

// /**
//  * Configure email transporter
//  */
// const createTransporter = () => {
//   if (!nodemailer) {
//     console.error('✗ Nodemailer not available');
//     return null;
//   }

//   if (!process.env.EMAIL_USER || !process.env.EMAIL_PASSWORD) {
//     console.warn('⚠️  Email not configured. Set EMAIL_USER and EMAIL_PASSWORD in .env');
//     return null;
//   }

//   try {
//     const transporter = nodemailer.createTransport({
//       service: 'gmail',
//       auth: {
//         user: process.env.EMAIL_USER,
//         pass: process.env.EMAIL_PASSWORD,
//       },
//     });

//     console.log('✓ Email transporter created');
//     return transporter;
//   } catch (err) {
//     console.error('✗ Failed to create transporter:', err.message);
//     return null;
//   }
// };

// /**
//  * Format currency in INR
//  */
// const formatINR = (value) => {
//   return new Intl.NumberFormat('en-IN', {
//     style: 'currency',
//     currency: 'INR',
//     maximumFractionDigits: 2,
//   }).format(Number(value || 0));
// };

// /**
//  * Send invoice email with PDF attachment (or HTML fallback if PDF fails)
//  */
// async function sendInvoiceEmail({ toEmail, invoice, invoiceHTML }) {
//   console.log('📧 Starting email send process...');
//   console.log('   To:', toEmail);

//   const transporter = createTransporter();

//   if (!transporter) {
//     const error = new Error('Email service not configured. Please set EMAIL_USER and EMAIL_PASSWORD in .env');
//     console.error('✗', error.message);
//     throw error;
//   }

//   // Extract invoice details
//   const invoiceNumber = invoice?.invoiceNumber || 'DRAFT';
//   const projectCode = invoice?.projectCode || 'N/A';
//   const consultantName = invoice?.consultantName || 'Consultant';
//   const total = invoice?.total || 0;
//   const formattedTotal = formatINR(total);

//   console.log('📄 Invoice details:');
//   console.log('   Number:', invoiceNumber);
//   console.log('   Project:', projectCode);
//   console.log('   Total:', formattedTotal);

//   // Email subject
//   const subject = `Invoice ${invoiceNumber} - ${projectCode}`;

//   // Create email HTML with invoice preview
//   const emailHTML = `
// <!DOCTYPE html>
// <html lang="en">
// <head>
//   <meta charset="UTF-8">
//   <title>Invoice ${invoiceNumber}</title>
//   <style>
//     body {
//       margin: 0;
//       padding: 0;
//       font-family: Arial, sans-serif;
//       background: #f5f5f5;
//     }
//     .container {
//       max-width: 600px;
//       margin: 30px auto;
//       background: #ffffff;
//       padding: 24px;
//       border-radius: 8px;
//       box-shadow: 0 2px 8px rgba(0,0,0,0.08);
//     }
//     .title {
//       font-size: 20px;
//       font-weight: 700;
//       margin-bottom: 12px;
//       color: #1f2937;
//     }
//     .meta {
//       font-size: 14px;
//       color: #374151;
//       margin-bottom: 16px;
//     }
//     .amount {
//       font-size: 18px;
//       font-weight: 700;
//       margin: 16px 0;
//       color: #111827;
//     }
//     .footer {
//       margin-top: 24px;
//       font-size: 12px;
//       color: #6b7280;
//       text-align: center;
//     }
//   </style>
// </head>
// <body>
//   <div class="container">
//     <div class="title">Invoice ${invoiceNumber}</div>

//     <div class="meta">
//       <p><strong>Project:</strong> ${projectCode}</p>
//       <p><strong>Total Amount:</strong> ${formattedTotal}</p>
//     </div>

//     <p>
//       Please find your invoice attached as a PDF.
//     </p>

//     <p>
//       If you have any questions, feel free to reply to this email.
//     </p>

//     <p>
//       Regards,<br />
//       <strong>${consultantName}</strong>
//     </p>

//     <div class="footer">
//       Invoice generated by Hourly.Design
//     </div>
//   </div>
// </body>
// </html>
// `.trim();


//   // Try to generate PDF, but fallback to HTML-only if it fails
//   let pdfBuffer = null;
//   let sendWithPDF = true;

//   if (invoiceHTML) {
//     try {
//       console.log('📨 Attempting to generate PDF attachment...');
//       pdfBuffer = await generateInvoicePDF(invoiceHTML, invoice);
//       console.log('✅ PDF generated successfully');
//     } catch (pdfError) {
//       console.error('⚠️  PDF generation failed, will send HTML-only email');
//       console.error('   Error:', pdfError.message);
//       sendWithPDF = false;
      
//       logger.warn({
//         error: pdfError.message,
//         invoiceNumber,
//         fallback: 'html-only'
//       }, 'PDF generation failed, using HTML fallback');
//     }
//   } else {
//     sendWithPDF = false;
//   }

//   // Send email (with or without PDF)
//   try {
//    const ccEmails = getInvoiceCCEmails();

// const mailOptions = {
//   from: `"Hourly Invoices" <${process.env.EMAIL_USER}>`,
//   to: toEmail,
//   cc: ccEmails, // ✅ AUTO CC FROM ENV
//   subject: subject,
//   html: emailHTML,
//   text: `Invoice ${invoiceNumber} - ${projectCode}\n\nTotal: ${formattedTotal}\n\nPlease view this email in an HTML-compatible client to see the invoice.`,
// };


//     // Add PDF attachment if available
//     if (sendWithPDF && pdfBuffer) {
//       const pdfFilename = `Invoice-${invoiceNumber}-${projectCode}.pdf`;
//       mailOptions.attachments = [
//         {
//           filename: pdfFilename,
//           content: pdfBuffer,
//           contentType: 'application/pdf',
//         }
//       ];
      
//       console.log('📧 Sending email with PDF attachment...');
//       console.log('   Attachment:', pdfFilename);
//       console.log('   Size:', (pdfBuffer.length / 1024).toFixed(2), 'KB');
//     } else {
//       console.log('📧 Sending HTML-only email (no PDF)...');
//     }

//     const info = await transporter.sendMail(mailOptions);

//     console.log('✅ Email sent successfully!');
//     console.log('   Message ID:', info.messageId);
//     console.log('   To:', toEmail);
//     console.log('   Format:', sendWithPDF ? 'HTML + PDF' : 'HTML only');

//     logger.info({ 
//       messageId: info.messageId, 
//       toEmail,
//       invoiceNumber,
//       projectCode,
//       hasPDF: sendWithPDF,
//       pdfSize: pdfBuffer ? pdfBuffer.length : 0,
//     }, `✅ Invoice email sent successfully ${sendWithPDF ? 'with PDF' : '(HTML only)'}`);

//     return {
//       success: true,
//       messageId: info.messageId,
//       format: sendWithPDF ? 'pdf' : 'html',
//       hasPDF: sendWithPDF,
//       filename: sendWithPDF ? `Invoice-${invoiceNumber}-${projectCode}.pdf` : null,
//     };

//   } catch (error) {
//     console.error('✗ Failed to send email');
//     console.error('   Error:', error.message);
//     console.error('   Code:', error.code);

//     if (error.code === 'EAUTH') {
//       console.error('   Issue: Email authentication failed');
//       console.error('   Tip: Check EMAIL_USER and EMAIL_PASSWORD in .env');
//     }

//     logger.error({ 
//       error: error.message, 
//       code: error.code,
//       toEmail,
//       invoiceNumber,
//     }, '❌ Failed to send invoice email');

//     throw error;
//   }
// }

// /**
//  * Verify email configuration
//  */
// async function verifyEmailConfig() {
//   console.log('\n🔍 Verifying email configuration...');

//   const transporter = createTransporter();
  
//   if (!transporter) {
//     console.log('✗ Email service not available\n');
//     return false;
//   }

//   try {
//     await transporter.verify();
//     console.log('✅ Email service verified successfully');
//     console.log(`   Email: ${process.env.EMAIL_USER}`);
//     console.log('   Service: Gmail SMTP');
//     return true;
//   } catch (error) {
//     console.error('✗ Email verification failed');
//     console.error('   Error:', error.message);
//     console.error('   Code:', error.code);
    
//     if (error.code === 'EAUTH') {
//       console.log('\n💡 Authentication failed. Check:');
//       console.log('   - Using App Password (not regular Gmail password)');
//       console.log('   - 2-Step Verification enabled');
//       console.log('   📖 https://support.google.com/accounts/answer/185833');
//     }
    
//     return false;
//   }
// }

// module.exports = {
//   sendInvoiceEmail,
//   verifyEmailConfig,
// };
// utils/invoiceEmailService.js
// Email service with PDF fallback for Windows stability

let nodemailer;
try {
  nodemailer = require('nodemailer');
  console.log('✓ Nodemailer loaded successfully');
} catch (err) {
  console.error('✗ Failed to load nodemailer:', err.message);
  console.error('  Run: npm install nodemailer');
}

const logger = require('./logger');
const { generateInvoicePDF } = require('./pdfGenerator');

/**
 * Parse CC emails from ENV
 */
const getInvoiceCCEmails = () => {
  const cc = process.env.ADMIN_CC_EMAIL;
  if (!cc) return undefined;

  return cc
    .split(',')
    .map(e => e.trim())
    .filter(Boolean);
};

/**
 * Configure email transporter
 */
const createTransporter = () => {
  if (!nodemailer) {
    console.error('✗ Nodemailer not available');
    return null;
  }

  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASSWORD) {
    console.warn('⚠️  Email not configured. Set EMAIL_USER and EMAIL_PASSWORD in .env');
    return null;
  }

  try {
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD,
      },
    });

    console.log('✓ Email transporter created');
    return transporter;
  } catch (err) {
    console.error('✗ Failed to create transporter:', err.message);
    return null;
  }
};

/**
 * Format currency in INR
 */
const formatINR = (value) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
  }).format(Number(value || 0));
};

/**
 * Send invoice email with PDF attachment (or HTML fallback if PDF fails)
 */
async function sendInvoiceEmail({ toEmail, invoice, invoiceHTML }) {
  console.log('📧 Starting email send process...');
  console.log('   To:', toEmail);

  const transporter = createTransporter();

  if (!transporter) {
    const error = new Error('Email service not configured. Please set EMAIL_USER and EMAIL_PASSWORD in .env');
    console.error('✗', error.message);
    throw error;
  }

  // Extract invoice details
  const invoiceNumber = invoice?.invoiceNumber || 'DRAFT';
  const projectCode = invoice?.projectCode || 'N/A';
  const consultantName = invoice?.consultantName || 'Consultant';
  const total = invoice?.total || 0;
  const formattedTotal = formatINR(total);

  console.log('📄 Invoice details:');
  console.log('   Number:', invoiceNumber);
  console.log('   Project:', projectCode);
  console.log('   Total:', formattedTotal);

  // Email subject
  const subject = `Invoice ${invoiceNumber} - ${projectCode}`;

  // ✅ PROFESSIONAL EMAIL TEMPLATE
  const emailHTML = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Invoice ${invoiceNumber}</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: #f5f5f5;
      color: #333;
      line-height: 1.6;
    }
    .container {
      max-width: 600px;
      margin: 40px auto;
      background: #ffffff;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 32px 24px;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      color: #ffffff;
      font-size: 28px;
      font-weight: 600;
      letter-spacing: -0.5px;
    }
    .header p {
      margin: 8px 0 0 0;
      color: rgba(255, 255, 255, 0.9);
      font-size: 14px;
    }
    .content {
      padding: 32px 24px;
    }
    .greeting {
      font-size: 16px;
      color: #333;
      margin-bottom: 20px;
    }
    .info-box {
      background: #f8f9fa;
      border-left: 4px solid #667eea;
      padding: 16px;
      margin: 24px 0;
      border-radius: 4px;
    }
    .info-row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #e9ecef;
    }
    .info-row:last-child {
      border-bottom: none;
    }
    .info-label {
      font-weight: 600;
      color: #495057;
      font-size: 14px;
    }
    .info-value {
      color: #212529;
      font-size: 14px;
    }
    .total-amount {
      background: #667eea;
      color: white;
      padding: 16px;
      border-radius: 6px;
      text-align: center;
      margin: 24px 0;
    }
    .total-amount .label {
      font-size: 14px;
      opacity: 0.9;
      margin-bottom: 4px;
    }
    .total-amount .amount {
      font-size: 32px;
      font-weight: 700;
      letter-spacing: -1px;
    }
    .attachment-notice {
      background: #e7f3ff;
      border: 1px solid #b3d9ff;
      padding: 16px;
      border-radius: 6px;
      margin: 24px 0;
      text-align: center;
      font-size: 14px;
      color: #004085;
    }
    .attachment-notice strong {
      display: block;
      margin-bottom: 4px;
      font-size: 15px;
    }
    .message {
      font-size: 15px;
      color: #495057;
      line-height: 1.7;
      margin: 20px 0;
    }
    .signature {
      margin-top: 32px;
      padding-top: 24px;
      border-top: 1px solid #e9ecef;
    }
    .signature-line {
      font-size: 15px;
      color: #495057;
      margin: 4px 0;
    }
    .signature-name {
      font-weight: 600;
      color: #212529;
      font-size: 16px;
    }
    .signature-company {
      color: #667eea;
      font-weight: 600;
    }
    .footer {
      background: #f8f9fa;
      padding: 24px;
      text-align: center;
      border-top: 1px solid #e9ecef;
    }
    .footer-text {
      font-size: 12px;
      color: #6c757d;
      margin: 4px 0;
    }
    .footer-link {
      color: #667eea;
      text-decoration: none;
      font-weight: 600;
    }
    .footer-link:hover {
      text-decoration: underline;
    }
    .divider {
      height: 1px;
      background: #e9ecef;
      margin: 24px 0;
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <h1>Invoice ${invoiceNumber}</h1>
      <p>Professional Services Invoice</p>
    </div>

    <!-- Content -->
    <div class="content">
      <div class="greeting">
        Dear Client,
      </div>

      <p class="message">
        Thank you for your continued partnership. Please find attached your invoice for the professional services rendered.
      </p>

      <!-- Invoice Details -->
      <div class="info-box">
        <div class="info-row">
          <span class="info-label">Invoice Number:</span>
          <span class="info-value">${invoiceNumber}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Project Code:</span>
          <span class="info-value">${projectCode}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Consultant:</span>
          <span class="info-value">${consultantName}</span>
        </div>
      </div>

      <!-- Total Amount -->
      <div class="total-amount">
        <div class="label">Invoice Amount</div>
        <div class="amount">${formattedTotal}</div>
      </div>

      <!-- Attachment Notice -->
      <div class="attachment-notice">
        <strong>📎 Invoice Attached</strong>
        Your detailed invoice is attached to this email as a PDF document.
      </div>

      <div class="divider"></div>

      <p class="message">
        Should you have any questions regarding this invoice or require any clarifications, please don't hesitate to reach out. We're here to assist you.
      </p>

      <!-- Signature -->
      <div class="signature">
        <div class="signature-line">Best regards,</div>
        <div class="signature-line signature-name">${consultantName}</div>
        <div class="signature-line signature-company">Hourly.Design</div>
      </div>
    </div>

    <!-- Footer -->
    <div class="footer">
      <div class="footer-text">
        This invoice was generated by <a href="https://hourly.design" class="footer-link">Hourly.Design</a>
      </div>
      <div class="footer-text" style="margin-top: 8px;">
        © ${new Date().getFullYear()} Hourly Ventures LLP. All rights reserved.
      </div>
    </div>
  </div>
</body>
</html>
`.trim();

  // Try to generate PDF, but fallback to HTML-only if it fails
  let pdfBuffer = null;
  let sendWithPDF = true;

  if (invoiceHTML) {
    try {
      console.log('📨 Attempting to generate PDF attachment...');
      pdfBuffer = await generateInvoicePDF(invoiceHTML, invoice);
      console.log('✅ PDF generated successfully');
    } catch (pdfError) {
      console.error('⚠️  PDF generation failed, will send HTML-only email');
      console.error('   Error:', pdfError.message);
      sendWithPDF = false;
      
      logger.warn({
        error: pdfError.message,
        invoiceNumber,
        fallback: 'html-only'
      }, 'PDF generation failed, using HTML fallback');
    }
  } else {
    sendWithPDF = false;
  }

  // Send email (with or without PDF)
  try {
    const ccEmails = getInvoiceCCEmails();

    const mailOptions = {
      from: `"Hourly Invoices" <${process.env.EMAIL_USER}>`,
      to: toEmail,
      cc: ccEmails, // ✅ AUTO CC FROM ENV
      subject: subject,
      html: emailHTML,
      text: `Invoice ${invoiceNumber}\n\nProject: ${projectCode}\nConsultant: ${consultantName}\nTotal Amount: ${formattedTotal}\n\nPlease view this email in an HTML-compatible client to see the full invoice details. A PDF copy is attached.\n\nBest regards,\n${consultantName}\nHourly.Design`,
    };

    // Add PDF attachment if available
    if (sendWithPDF && pdfBuffer) {
      const pdfFilename = `Invoice-${invoiceNumber}-${projectCode}.pdf`;
      mailOptions.attachments = [
        {
          filename: pdfFilename,
          content: pdfBuffer,
          contentType: 'application/pdf',
        }
      ];
      
      console.log('📧 Sending email with PDF attachment...');
      console.log('   Attachment:', pdfFilename);
      console.log('   Size:', (pdfBuffer.length / 1024).toFixed(2), 'KB');
    } else {
      console.log('📧 Sending HTML-only email (no PDF)...');
    }

    const info = await transporter.sendMail(mailOptions);

    console.log('✅ Email sent successfully!');
    console.log('   Message ID:', info.messageId);
    console.log('   To:', toEmail);
    console.log('   Format:', sendWithPDF ? 'HTML + PDF' : 'HTML only');

    logger.info({ 
      messageId: info.messageId, 
      toEmail,
      invoiceNumber,
      projectCode,
      hasPDF: sendWithPDF,
      pdfSize: pdfBuffer ? pdfBuffer.length : 0,
    }, `✅ Invoice email sent successfully ${sendWithPDF ? 'with PDF' : '(HTML only)'}`);

    return {
      success: true,
      messageId: info.messageId,
      format: sendWithPDF ? 'pdf' : 'html',
      hasPDF: sendWithPDF,
      filename: sendWithPDF ? `Invoice-${invoiceNumber}-${projectCode}.pdf` : null,
    };

  } catch (error) {
    console.error('✗ Failed to send email');
    console.error('   Error:', error.message);
    console.error('   Code:', error.code);

    if (error.code === 'EAUTH') {
      console.error('   Issue: Email authentication failed');
      console.error('   Tip: Check EMAIL_USER and EMAIL_PASSWORD in .env');
    }

    logger.error({ 
      error: error.message, 
      code: error.code,
      toEmail,
      invoiceNumber,
    }, '❌ Failed to send invoice email');

    throw error;
  }
}

/**
 * Verify email configuration
 */
async function verifyEmailConfig() {
  console.log('\n🔍 Verifying email configuration...');

  const transporter = createTransporter();
  
  if (!transporter) {
    console.log('✗ Email service not available\n');
    return false;
  }

  try {
    await transporter.verify();
    console.log('✅ Email service verified successfully');
    console.log(`   Email: ${process.env.EMAIL_USER}`);
    console.log('   Service: Gmail SMTP');
    return true;
  } catch (error) {
    console.error('✗ Email verification failed');
    console.error('   Error:', error.message);
    console.error('   Code:', error.code);
    
    if (error.code === 'EAUTH') {
      console.log('\n💡 Authentication failed. Check:');
      console.log('   - Using App Password (not regular Gmail password)');
      console.log('   - 2-Step Verification enabled');
      console.log('   📖 https://support.google.com/accounts/answer/185833');
    }
    
    return false;
  }
}

module.exports = {
  sendInvoiceEmail,
  verifyEmailConfig,
};